/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_values[3];
int lcl_whole = 0;
long lcl_fraction = 32768L; /* 0.5 */
long lcl_direct = 32768L; /* 0.5 */

static void lcl__init(void)
{
    lcl_whole = 3;
    lcl_fraction = (((long)3 << 16) + 32768L /* 0.5 */);
    lcl_direct = ((long)3 << 16);
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_whole, 48, 36, 7);
    gt_print_num(lcl_fraction, 48, 60, 254);
    gt_print_num(lcl_direct, 48, 84, 31);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
