/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

long lcl_literal_edge = 2147483647L; /* 32767.99998474121 */
long lcl_runtime_edge = -2147483648L; /* -32768 */
long lcl_ordinary = 163840L; /* 2.5 */

static void lcl__init(void)
{
    lcl_runtime_edge = gt_absf(lcl_runtime_edge);
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_num(lcl_literal_edge, 34, 29, 7);
    gt_print_num(lcl_runtime_edge, 34, 53, 254);
    gt_print_num(lcl_ordinary, 34, 77, 31);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
