/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

long lcl_values[3] = {
    655360L, 1343488L, -196608L
};
unsigned char lcl_piped[2] = {
    4, 5
};
unsigned char lcl_digits[2] = {
    12, 34
};

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_num(lcl_values[0], 44, 2, 7);
    gt_print_num(lcl_values[1], 44, 17, 254);
    gt_print_num(lcl_values[2], 44, 32, 31);
    gt_print_int(lcl_piped[0], 44, 47, 190);
    gt_print_int(lcl_piped[1], 44, 62, 62);
    gt_print_int(lcl_digits[0], 44, 77, 91);
    gt_print_int(lcl_digits[1], 44, 92, 94);
    gt_print_int(3, 44, 107, 6);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
