/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_floor = -4;
int lcl_ceiling = -3;
int lcl_sign = 1;
long lcl_low = -163840L; /* -2.5 */
int lcl_default_max = 0;
int lcl_middle = 7;
unsigned char lcl_bytes[4];

static void lcl__init(void)
{
    lcl_bytes[3] = 42;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_floor, 44, 2, 7);
    gt_print_int(lcl_ceiling, 44, 17, 254);
    gt_print_int(lcl_sign, 44, 32, 31);
    gt_print_num(lcl_low, 44, 47, 190);
    gt_print_int(lcl_default_max, 44, 62, 62);
    gt_print_int(lcl_middle, 44, 77, 91);
    gt_print_int(4, 44, 92, 94);
    gt_print_int(lcl_bytes[3], 44, 107, 6);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
