/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_phase = 0;

static void lcl__init(void)
{
}

static void lcl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        lcl_phase = gt_ifmod((lcl_phase + 1), 3);
    }
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_clip(16, 16, 96, 80, 0);
    if ((lcl_phase == 1)) {
        gt_clip(32, 28, 64, 48, ((1) ? 1 : 0));
    } else if ((lcl_phase == 2)) {
        gt_clip(48, 36, 32, 32, ((1) ? 1 : 0));
    }
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 127, gt_a3 = 127, gt_a4 = 169, gt_rectfill_z());
    (gt_a0 = 64, gt_a1 = 56, gt_a2 = 45, gt_a3 = 190, gt_circfill_z());
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 127, gt_a3 = 111, gt_a4 = 31, gt_line_z());
    (gt_a0 = 8, gt_a1 = 8, gt_a2 = 119, gt_a3 = 103, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 64, gt_a1 = 56, gt_a2 = 38, gt_a3 = 7, gt_circ_z());
    gt_clip_reset();
    gt_print("clip phase", 34, 2, 7);
    gt_print_int(lcl_phase, 61, 9, 7);
    gt_print("a: shrink", 43, 116, 6);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
