/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

unsigned char lcl_things_id[4];
unsigned char lcl_things_used[4];
unsigned char lcl_things_free;   /* free-chain head, +1-encoded (0 = empty) */
int lcl_things_n;
unsigned char lcl_things_hi;
unsigned char lcl_slots[3];
int lcl_phase = 0;

static void lcl__init(void)
{
    { unsigned char L_s0; if (lcl_things_free) { L_s0 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s0]; } else L_s0 = lcl_things_hi; if (L_s0 < 4) { lcl_things_used[L_s0] = 1; ++lcl_things_n; if (L_s0 >= lcl_things_hi) lcl_things_hi = L_s0 + 1; lcl_things_id[L_s0] = 1; } }
    { unsigned char L_s1; if (lcl_things_free) { L_s1 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s1]; } else L_s1 = lcl_things_hi; if (L_s1 < 4) { lcl_things_used[L_s1] = 1; ++lcl_things_n; if (L_s1 >= lcl_things_hi) lcl_things_hi = L_s1 + 1; lcl_things_id[L_s1] = 2; } }
}

static void lcl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        lcl_phase = gt_ifmod((lcl_phase + 1), 3);
        if ((lcl_phase == 1)) {
            { unsigned char L_s2; if (lcl_things_free) { L_s2 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s2]; } else L_s2 = lcl_things_hi; if (L_s2 < 4) { lcl_things_used[L_s2] = 1; ++lcl_things_n; if (L_s2 >= lcl_things_hi) lcl_things_hi = L_s2 + 1; lcl_things_id[L_s2] = 3; } }
        } else if ((lcl_phase == 2)) {
            { unsigned char L_p3;
                for (L_p3 = 0; L_p3 < lcl_things_hi; ++L_p3) {
                    if (!lcl_things_used[L_p3]) continue;
                    (lcl_things_used[L_p3] = 0, lcl_things_id[L_p3] = lcl_things_free, lcl_things_free = (unsigned char)(L_p3 + 1), (--lcl_things_n == 0 ? (lcl_things_hi = 0, lcl_things_free = 0) : 0), (void)0);
                }
            }
        } else if ((lcl_phase == 0)) {
            { unsigned char L_s4; if (lcl_things_free) { L_s4 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s4]; } else L_s4 = lcl_things_hi; if (L_s4 < 4) { lcl_things_used[L_s4] = 1; ++lcl_things_n; if (L_s4 >= lcl_things_hi) lcl_things_hi = L_s4 + 1; lcl_things_id[L_s4] = 1; } }
            { unsigned char L_s5; if (lcl_things_free) { L_s5 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s5]; } else L_s5 = lcl_things_hi; if (L_s5 < 4) { lcl_things_used[L_s5] = 1; ++lcl_things_n; if (L_s5 >= lcl_things_hi) lcl_things_hi = L_s5 + 1; lcl_things_id[L_s5] = 2; } }
        }
    }
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("count pool", 20, 32, 7);
    gt_print_int(lcl_things_n, 88, 32, 7);
    gt_print("hash pool", 20, 48, 7);
    gt_print_int(lcl_things_n, 88, 48, 7);
    gt_print("count array", 20, 64, 7);
    gt_print_int(3, 88, 64, 7);
    gt_print("press a", 44, 88, 6);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
