/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_ai = -9;
int lcl_bi = 2;
long lcl_af = -622592L; /* -9.5 */
int lcl_bf = 2;

static void lcl__update(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("-9 fd 2", 20, 24, 7);
    gt_print_int(gt_ifdiv(lcl_ai, lcl_bi), 82, 24, 7);
    gt_print("9 fd -2", 20, 40, 7);
    gt_print_int(gt_ifdiv((-lcl_ai), (-lcl_bi)), 82, 40, 7);
    gt_print("-9.5 fd 2", 20, 56, 7);
    gt_print_int((int)((fa = lcl_af, fb = ((long)lcl_bf << 16), gt_fdiv_zp()) >> 16), 82, 56, 7);
    gt_print("9.5 fd -2", 20, 72, 7);
    gt_print_int((int)((fa = (-lcl_af), fb = ((long)(-lcl_bf) << 16), gt_fdiv_zp()) >> 16), 82, 72, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
