/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__draw(void);

int lcl_imported10 = 0;
int lcl_imported10bit1 = 0;
int lcl_imported10bit2 = 0;
int lcl_mutated10 = 0;
int lcl_mutated10bit1 = 0;
int lcl_mutated10bit2 = 0;
int lcl_replaced11 = 0;

static void lcl__init(void)
{
    lcl_imported10 = gt_fget(10, -1);
    lcl_imported10bit1 = gt_fget(10, 1);
    lcl_imported10bit2 = gt_fget(10, 2);
    gt_fset(10, 2, ((1) ? 1 : 0));
    gt_fset(10, 1, ((0) ? 1 : 0));
    lcl_mutated10 = gt_fget(10, -1);
    lcl_mutated10bit1 = gt_fget(10, 1);
    lcl_mutated10bit2 = gt_fget(10, 2);
    gt_fset(11, -1, 9);
    lcl_replaced11 = gt_fget(11, -1);
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_imported10, 4, 8, 7);
    gt_print_int(lcl_imported10bit1, 4, 16, 7);
    gt_print_int(lcl_imported10bit2, 4, 24, 7);
    gt_print_int(lcl_mutated10, 4, 40, 7);
    gt_print_int(lcl_mutated10bit1, 4, 48, 7);
    gt_print_int(lcl_mutated10bit2, 4, 56, 7);
    gt_print_int(lcl_replaced11, 4, 72, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__draw();
        gt_endframe();
    }
}
