/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_width = 8;
long lcl_fraction = 229376L; /* 3.5 */
int lcl_empty = 0;
unsigned char lcl_bytes[4];

static void lcl__init(void)
{
    lcl_bytes[3] = 42;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_width, 44, 20, 7);
    gt_print_num(lcl_fraction, 44, 38, 254);
    gt_print_int(lcl_empty, 44, 56, 31);
    gt_print_int(4, 44, 74, 190);
    gt_print_int(lcl_bytes[3], 44, 92, 62);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
