/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_width = 8;
long lcl_fraction = 229376L; /* 3.5 */
unsigned char lcl_bytes[4];

static void lcl__init(void)
{
    lcl_bytes[3] = 42;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_width, 44, 24, 7);
    gt_print_num(lcl_fraction, 44, 44, 254);
    gt_print_int(4, 44, 64, 31);
    gt_print_int(lcl_bytes[3], 44, 84, 190);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
