/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__draw(void);

const unsigned char lcl___p8map[8] = {
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08
};

static void lcl__init(void)
{
    gt_mset(lcl___p8map, 2, 0, 7);
    gt_mset(lcl___p8map, 2, 0, 6);
    gt_mset(lcl___p8map, 4, 0, 8);
    gt_mset(lcl___p8map, 4, 0, 5);
    gt_mset(lcl___p8map, (-1), 0, 9);
    gt_mset(lcl___p8map, 128, 0, 9);
    gt_mset(lcl___p8map, 0, 32, 9);
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_map(lcl___p8map, 128, 0, 0, 0, 0, 8, 1, -1);
    gt_print_int(gt_mget(lcl___p8map, 2, 0), 4, 16, 7);
    gt_print_int(gt_mget(lcl___p8map, 4, 0), 4, 24, 7);
    gt_print_int(gt_mget(lcl___p8map, 6, 0), 4, 32, 7);
    gt_print_int(gt_mget(lcl___p8map, (-1), 0), 4, 48, 7);
    gt_print_int(gt_mget(lcl___p8map, 128, 0), 4, 56, 7);
    gt_print_int(gt_mget(lcl___p8map, 0, 32), 4, 64, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__draw();
        gt_endframe();
    }
}
