/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

int lcl_changed = 0;

static void lcl__update60(void)
{
    if (((gt_pad0 & 16u) != 0)) {
        gt_fset(2, 0, ((1) ? 1 : 0));
        gt_fset(3, 2, ((0) ? 1 : 0));
        lcl_changed = 1;
    }
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("all", 2, 4, 7);
    gt_map(lcl___p8map, 128, 0, 0, 40, 2, 3, 1, -1);
    gt_print("flag0", 2, 28, 7);
    gt_map(lcl___p8map, 128, 0, 0, 40, 26, 3, 1, 1);
    gt_print("flag2", 2, 52, 7);
    gt_map(lcl___p8map, 128, 0, 0, 40, 50, 3, 1, 4);
    gt_print("flag0|2", 2, 76, 7);
    gt_map(lcl___p8map, 128, 0, 0, 40, 74, 3, 1, 5);
    gt_print_int(gt_fget(1, -1), 72, 4, 7);
    gt_print_int(gt_fget(2, -1), 88, 4, 7);
    gt_print_int(gt_fget(3, -1), 104, 4, 7);
    if ((lcl_changed != 0)) {
        gt_print("changed", 2, 104, 7);
    } else {
        gt_print("press a", 2, 104, 7);
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
