/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_original = 0;
int lcl_stage = 1;

static void lcl__init(void)
{
    lcl_original = gt_mget(lcl___p8map, 0, 40);
    gt_mset(lcl___p8map, 0, 40, 1);
}

static void lcl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        lcl_stage = (lcl_stage + 1);
        if ((lcl_stage > 2)) {
            lcl_stage = 0;
        }
        if ((lcl_stage == 0)) {
            gt_mset(lcl___p8map, 0, 40, lcl_original);
        } else {
            gt_mset(lcl___p8map, 0, 40, lcl_stage);
        }
    }
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("row", 4, 8, 7);
    gt_print_int(40, 44, 8, 7);
    gt_print("original", 4, 20, 7);
    gt_print_int(lcl_original, 60, 20, 7);
    gt_print("mget", 4, 32, 7);
    gt_print_int(gt_mget(lcl___p8map, 0, 40), 60, 32, 7);
    gt_print("flag0", 4, 52, 7);
    gt_map(lcl___p8map, 128, 0, 40, 72, 50, 1, 1, 1);
    gt_print("flag2", 4, 72, 7);
    gt_map(lcl___p8map, 128, 0, 40, 72, 70, 1, 1, 4);
    gt_print("press a: 1 2 0", 4, 104, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
