/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_first = 0;
int lcl_second = 0;
int lcl_last = 0;

static void lcl__init(void)
{
    lcl_first = 64;
    lcl_second = 50;
    lcl_last = 101;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("ord @", 28, 32, 7);
    gt_print_int(lcl_first, 80, 32, 7);
    gt_print("ord 123 2", 28, 52, 7);
    gt_print_int(lcl_second, 80, 52, 7);
    gt_print("ord game 4", 28, 72, 7);
    gt_print_int(lcl_last, 80, 72, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
