/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

long lcl_quarter = 16384L; /* 0.25 */
long lcl_negative = -229376L; /* -3.5 */
long lcl_rounded = 80908L; /* 1.23456 */
int lcl_minimum = -32768;

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("quarter", 12, 24, 7);
    gt_print_num(lcl_quarter, 72, 24, 254);
    gt_print("negative", 12, 44, 7);
    gt_print_num(lcl_negative, 72, 44, 254);
    gt_print("rounded", 12, 64, 7);
    gt_print_num(lcl_rounded, 72, 64, 254);
    gt_print("minimum", 12, 84, 7);
    gt_print_int(lcl_minimum, 72, 84, 254);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
