/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

unsigned char lcl_things_id[4];
unsigned char lcl_things_used[4];
unsigned char lcl_things_order[4];  /* live slots in insertion order */
unsigned char lcl_things_free;   /* free-chain head, +1-encoded (0 = empty) */
int lcl_things_n;
unsigned char lcl_things_hi;
int lcl_phase = 0;

static void lcl__init(void)
{
    { unsigned char L_s0; if (lcl_things_free) { L_s0 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s0]; } else L_s0 = lcl_things_hi; if (L_s0 < 4) { lcl_things_used[L_s0] = 1; lcl_things_order[lcl_things_n++] = L_s0; if (L_s0 >= lcl_things_hi) lcl_things_hi = L_s0 + 1; lcl_things_id[L_s0] = 10; } }
    { unsigned char L_s1; if (lcl_things_free) { L_s1 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s1]; } else L_s1 = lcl_things_hi; if (L_s1 < 4) { lcl_things_used[L_s1] = 1; lcl_things_order[lcl_things_n++] = L_s1; if (L_s1 >= lcl_things_hi) lcl_things_hi = L_s1 + 1; lcl_things_id[L_s1] = 20; } }
    { unsigned char L_s2; if (lcl_things_free) { L_s2 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s2]; } else L_s2 = lcl_things_hi; if (L_s2 < 4) { lcl_things_used[L_s2] = 1; lcl_things_order[lcl_things_n++] = L_s2; if (L_s2 >= lcl_things_hi) lcl_things_hi = L_s2 + 1; lcl_things_id[L_s2] = 30; } }
}

static void lcl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        if ((lcl_phase == 0)) {
            { unsigned char L_o3, L_p4;
                for (L_o3 = 0; L_o3 < lcl_things_n; ++L_o3) {
                    L_p4 = lcl_things_order[L_o3];
                    if ((lcl_things_id[L_p4] == 10)) {
                        { unsigned char L_o5; lcl_things_used[L_p4] = 0; lcl_things_id[L_p4] = lcl_things_free; lcl_things_free = (unsigned char)(L_p4 + 1); --lcl_things_n; for (L_o5 = L_o3; L_o5 < lcl_things_n; ++L_o5) lcl_things_order[L_o5] = lcl_things_order[L_o5 + 1]; --L_o3; if (!lcl_things_n) { lcl_things_hi = 0; lcl_things_free = 0; } }
                        break;
                    }
                }
            }
            { unsigned char L_s6; if (lcl_things_free) { L_s6 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s6]; } else L_s6 = lcl_things_hi; if (L_s6 < 4) { lcl_things_used[L_s6] = 1; lcl_things_order[lcl_things_n++] = L_s6; if (L_s6 >= lcl_things_hi) lcl_things_hi = L_s6 + 1; lcl_things_id[L_s6] = 40; } }
            lcl_phase = 1;
        } else if ((lcl_phase == 1)) {
            { int L_i7 = 2 - 1; if (L_i7 >= 0 && L_i7 < lcl_things_n) { unsigned char L_s8 = lcl_things_order[L_i7]; unsigned char L_o9; lcl_things_used[L_s8] = 0; lcl_things_id[L_s8] = lcl_things_free; lcl_things_free = (unsigned char)(L_s8 + 1); --lcl_things_n; for (L_o9 = (unsigned char)L_i7; L_o9 < lcl_things_n; ++L_o9) lcl_things_order[L_o9] = lcl_things_order[L_o9 + 1]; if (!lcl_things_n) { lcl_things_hi = 0; lcl_things_free = 0; } } }
            lcl_phase = 2;
        } else if ((lcl_phase == 2)) {
            { unsigned char L_s10; if (lcl_things_free) { L_s10 = (unsigned char)(lcl_things_free - 1); lcl_things_free = (unsigned char)lcl_things_id[L_s10]; } else L_s10 = lcl_things_hi; if (L_s10 < 4) { lcl_things_used[L_s10] = 1; lcl_things_order[lcl_things_n++] = L_s10; if (L_s10 >= lcl_things_hi) lcl_things_hi = L_s10 + 1; lcl_things_id[L_s10] = 50; } }
            lcl_phase = 3;
        }
    }
}

static void lcl__draw(void)
{
    { int lcl_y = 38;
        gt_cls(0);
        gt_print("phase", 34, 18, 7);
        gt_print_int(lcl_phase, 70, 18, 7);
        { unsigned char L_o11, L_p12;
            for (L_o11 = 0; L_o11 < lcl_things_n; ++L_o11) {
                L_p12 = lcl_things_order[L_o11];
                gt_print_int(lcl_things_id[L_p12], 54, lcl_y, 7);
                lcl_y = (lcl_y + 12);
            }
        }
        gt_print("press a", 42, 102, 6);
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
