/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
}

static void lcl__draw(void)
{
    gt_cls(169);
    gt_palt(1);
    (gt_a0 = 0, gt_a1 = 24, gt_a2 = 34, gt_a3 = 1, gt_a4 = 1, gt_a5 = 0 | (0 << 1), gt_spr_z());
    gt_palt(((0) ? 1 : 0));
    (gt_a0 = 0, gt_a1 = 60, gt_a2 = 34, gt_a3 = 1, gt_a4 = 1, gt_a5 = 0 | (0 << 1), gt_spr_z());
    gt_palt(1);
    (gt_a0 = 0, gt_a1 = 96, gt_a2 = 34, gt_a3 = 1, gt_a4 = 1, gt_a5 = 0 | (0 << 1), gt_spr_z());
    gt_palt(1);
    gt_sspr(0, 0, 8, 8, 20, 66, 16, 16, 0 | 0);
    gt_palt(((0) ? 1 : 0));
    gt_sspr(0, 0, 8, 8, 56, 66, 16, 16, 0 | 0);
    gt_palt(1);
    gt_sspr(0, 0, 8, 8, 92, 66, 16, 16, 0 | 0);
    (gt_a0 = 22, gt_a1 = 32, gt_a2 = 33, gt_a3 = 43, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 58, gt_a1 = 32, gt_a2 = 69, gt_a3 = 43, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 94, gt_a1 = 32, gt_a2 = 105, gt_a3 = 43, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 18, gt_a1 = 64, gt_a2 = 37, gt_a3 = 83, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 54, gt_a1 = 64, gt_a2 = 73, gt_a3 = 83, gt_a4 = 7, gt_rect_z());
    (gt_a0 = 90, gt_a1 = 64, gt_a2 = 109, gt_a3 = 83, gt_a4 = 7, gt_rect_z());
    gt_print("transparent opaque reset", 19, 12, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
