/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_code = 65;
long lcl_decimal = 819200L; /* 12.5 */
long lcl_nested = -229376L; /* -3.5 */
unsigned char lcl_bytes[4];

static void lcl__init(void)
{
    lcl_bytes[3] = 42;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(lcl_code, 44, 29, 7);
    gt_print_num(lcl_decimal, 44, 47, 254);
    gt_print_num(lcl_nested, 44, 65, 31);
    gt_print_int(4, 44, 83, 190);
    gt_print_int(lcl_bytes[3], 44, 101, 62);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
