/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_code = 0;

static void lcl__init(void)
{
    lcl_code = 65;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("ord chr", 20, 28, 7);
    gt_print_int(lcl_code, 84, 28, 254);
    gt_print("sub chr", 20, 48, 7);
    gt_print("ell", 84, 48, 254);
    gt_print("tostr", 20, 68, 7);
    gt_print("-3.5", 84, 68, 254);
    gt_print("rounded", 20, 88, 7);
    gt_print("1.2346", 84, 88, 254);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
