/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_loaded = 0;
long lcl_count = 0L; /* 0 */
long lcl_fraction = 0L; /* 0 */

static void lcl__init(void)
{
    if (gt_cartdata(0x9be79f3fUL)) {
        lcl_loaded = 1;
    }
    lcl_count = gt_dget(0);
    lcl_fraction = gt_dget(1);
    gt_dset(0, (lcl_count + 65536L));
    gt_dset(1, (lcl_fraction + 32768L /* 0.5 */));
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("loaded", 4, 8, 7);
    gt_print_int(lcl_loaded, 52, 8, 7);
    gt_print("count", 4, 24, 7);
    gt_print_num(lcl_count, 52, 24, 7);
    gt_print("half x2", 4, 40, 7);
    gt_print_num((lcl_fraction << 1), 52, 40, 7);
    gt_print("restart emulator", 4, 72, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
