/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_code = 0;

static void lcl__init(void)
{
    lcl_code = 97;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("concat", 12, 18, 7);
    gt_print("score 12.5", 76, 18, 254);
    gt_print("ord concat", 12, 38, 7);
    gt_print_int(lcl_code, 76, 38, 254);
    gt_print("sub concat", 12, 58, 7);
    gt_print("12.5", 76, 58, 254);
    gt_print("tonum const", 12, 78, 7);
    gt_print_num(819200L, 76, 78, 254);
    gt_print("empty", 12, 98, 7);
    gt_print("ab", 76, 98, 254);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
