/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__draw(void);

int lcl_loaded = -1;
int lcl_written = -1;

static void lcl__init(void)
{
    lcl_loaded = gt_sget(0, 0);
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 91, gt_sset_z());
    lcl_written = gt_sget(0, 0);
}

static void lcl__draw(void)
{
    gt_cls(169);
    gt_print("quad0 loaded", 4, 12, 7);
    gt_print_int(lcl_loaded, 80, 12, 7);
    gt_print("quad0 write", 4, 28, 7);
    gt_print_int(lcl_written, 80, 28, 7);
    gt_print("expect 0 91", 4, 48, 7);
    (gt_a0 = 16, gt_a1 = 68, gt_a2 = 47, gt_a3 = 99, gt_a4 = lcl_loaded, gt_rectfill_z());
    (gt_a0 = 80, gt_a1 = 68, gt_a2 = 111, gt_a3 = 99, gt_a4 = lcl_written, gt_rectfill_z());
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__draw();
        gt_endframe();
    }
}
