/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__draw(void);

int lcl_first = 0;
int lcl_second = 0;
int lcl_outside = 1;

static void lcl__init(void)
{
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 91, gt_sset_z());
    lcl_first = gt_sget(0, 0);
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 62, gt_sset_z());
    lcl_second = gt_sget(0, 0);
    lcl_outside = gt_sget((-1), 0);
}

static void lcl__draw(void)
{
    gt_cls(169);
    gt_print("sget", 4, 4, 7);
    gt_print("first", 4, 20, 7);
    gt_print_int(lcl_first, 52, 20, 7);
    gt_print("second", 4, 32, 7);
    gt_print_int(lcl_second, 52, 32, 7);
    gt_print("outside", 4, 44, 7);
    gt_print_int(lcl_outside, 52, 44, 7);
    (gt_a0 = 4, gt_a1 = 60, gt_a2 = 27, gt_a3 = 83, gt_a4 = lcl_first, gt_rectfill_z());
    (gt_a0 = 36, gt_a1 = 60, gt_a2 = 59, gt_a3 = 83, gt_a4 = lcl_second, gt_rectfill_z());
    (gt_a0 = 0, gt_a1 = 76, gt_a2 = 60, gt_a3 = 3, gt_a4 = 3, gt_a5 = 0 | (0 << 1), gt_spr_z());
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__draw();
        gt_endframe();
    }
}
