/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

long lcl_values[3] = {
    655360L, 1343488L, -196608L
};
unsigned char lcl_digits[3] = {
    1, 2, 3
};

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_int(3, 60, 22, 7);
    gt_print_num(lcl_values[0], 48, 42, 91);
    gt_print_num(lcl_values[1], 48, 62, 62);
    gt_print_num(lcl_values[2], 48, 82, 31);
    gt_print_int(((lcl_digits[0] + lcl_digits[1]) + lcl_digits[2]), 60, 102, 254);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
