/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

long lcl_folded = 92681L; /* 1.4141998291015625 */
long lcl_runtime = 131072L; /* 2 */
int lcl_negative = 0;

static void lcl__init(void)
{
    lcl_runtime = gt_fsqrt(lcl_runtime);
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_num(lcl_folded, 34, 29, 7);
    gt_print_num(lcl_runtime, 34, 53, 254);
    gt_print_int(lcl_negative, 34, 77, 31);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
