/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

long lcl_joined = 32768L; /* 0.5 */
long lcl_sliced = 32768L; /* 0.5 */
int lcl_bytes = 0;
long lcl_roundtrip = 32768L; /* 0.5 */

static void lcl__init(void)
{
    lcl_joined = 819200L;
    lcl_sliced = -229376L;
    lcl_bytes = 42;
    lcl_roundtrip = 16384L;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print_num(lcl_joined, 44, 24, 7);
    gt_print_num(lcl_sliced, 44, 44, 254);
    gt_print_int(lcl_bytes, 44, 64, 31);
    gt_print_num(lcl_roundtrip, 44, 84, 190);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
