/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("function", 40, 24, 7);
    gt_print("function", 40, 44, 254);
    { int lcl_helper = 2;
        { int lcl_rnd = 3;
            gt_print("number", 40, 64, 31);
            gt_print("number", 40, 84, 190);
        }
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
