/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update60(void);
static void lcl__draw(void);

int lcl_n = 1;
unsigned char lcl_ps_used[2];
unsigned char lcl_ps_order[2];  /* live slots in insertion order */
unsigned char lcl_ps_free;   /* free-chain head, +1-encoded (0 = empty) */
int lcl_ps_n;
unsigned char lcl_ps_hi;
unsigned char lcl_bytes[2];

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("number", 36, 18, 7);
    gt_print("boolean", 36, 32, 91);
    gt_print("string", 36, 46, 62);
    gt_print("nil", 36, 60, 31);
    gt_print("table", 36, 74, 254);
    gt_print("table", 36, 88, 190);
    gt_print("function", 36, 102, 140);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
