/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_whole = 0;
long lcl_negative = 0L; /* 0 */
long lcl_fraction = 0L; /* 0 */

static void lcl__init(void)
{
    lcl_whole = 42;
    lcl_negative = -229376L;
    lcl_fraction = 16384L;
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(0);
    gt_print("whole 42", 20, 28, 7);
    if ((lcl_whole == 42)) {
        (gt_a0 = 92, gt_a1 = 27, gt_a2 = 103, gt_a3 = 36, gt_a4 = 254, gt_rectfill_z());
    } else {
        (gt_a0 = 92, gt_a1 = 27, gt_a2 = 103, gt_a3 = 36, gt_a4 = 91, gt_rectfill_z());
    }
    gt_print("negative -3.5", 20, 52, 7);
    if ((lcl_negative == (-229376L /* 3.5 */))) {
        (gt_a0 = 92, gt_a1 = 51, gt_a2 = 103, gt_a3 = 60, gt_a4 = 254, gt_rectfill_z());
    } else {
        (gt_a0 = 92, gt_a1 = 51, gt_a2 = 103, gt_a3 = 60, gt_a4 = 91, gt_rectfill_z());
    }
    gt_print("fraction .25", 20, 76, 7);
    if ((lcl_fraction == 16384L /* 0.25 */)) {
        (gt_a0 = 92, gt_a1 = 75, gt_a2 = 103, gt_a3 = 84, gt_a4 = 254, gt_rectfill_z());
    } else {
        (gt_a0 = 92, gt_a1 = 75, gt_a2 = 103, gt_a3 = 84, gt_a4 = 91, gt_rectfill_z());
    }
    gt_print("green = exact", 34, 100, 6);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
