/* generated by gtlua from synth-minmax.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int lcl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int lcl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { long lcl_d = gt_absf(((long)(-5) << 16));
                }
            }
        }
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
